### PR TITLE
mystuff-56 CD jenkins pipeline for kubernetes

### LINKED ISSUE #56: CD jenkins pipeline for kubernetes

### PR DESCRIPTION
**Pull request by Max-Levitskiy**
Closes #56

### CODE REVIEW

**Comment by Max-Levitskiy** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by Max-Levitskiy** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by cicd-webtree** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by cicd-webtree** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by cicd-webtree** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by cicd-webtree** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Comment by cicd-webtree** [comment]
Test system provisioned on url https://mystuff-pr-82.dev.webtree.org. Backend: https://back.mystuff-dev-pr-82.webtree.org

**Pull request merged**
